### PR TITLE
add Composer resources to autoload needed libraries

### PR DESCRIPTION
**Pull request by takahi-i**

### CODE REVIEW

**Comment by takahi-i** [comment]
looks like the following problem. 

http://help.pagodabox.com/customer/portal/questions/6193893-failed-to-download-doctrine-common-from-dist-could-not-authenticate-against-github-com/

**Comment by cbxp** [comment]
I didn't add composer as a dependency on purpose, actually. Composer is a dependency itself that you need to install, and if we use it only to install phpunit, then it is easier and cleaner to install phpunit without composer. Don't you think so?

**Comment by takahi-i** [comment]
Well you right that this plugin is not depend on only phpunit but it takes quite long time to understand the version of phpunit. The latest version of  phpunit does not work in IntelliJ envrionments and looks that only v3.7x are compatible with IntelliJ IDEA. To avoid such a problem by new developers, I would like to provide a way to install dependencies with the best versions, though composer is not the best solution.

**Comment by takahi-i** [comment]
I withdraw this pr just adding phpunit source would be better

**Pull request closed without merging**
